import os
import json
from typing import List

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from prompt.extractor import extract_entities
from prompt.evaluator import evaluate_importance
from prompt.trust_checker import trust_checker, extract_key_sections
from prompt.doc_parser import extract_metadata_heuristics

DOCLING_FOLDER = "docling_docs"

# ===== FastAPI initialization =====
app = FastAPI(
    title="LLM API",
    description="API wrapper for prompt-based document analysis",
    version="1.0",
)

# Allow frontend (browser) to access this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ===== Utility functions =====
def load_all_json_docs(folder: str):
    """
    Load all JSON documents generated by docling.

    Returns:
        List of dicts:
        [
            {
                "id": "filename.json",
                "data": <parsed json>
            }
        ]
    """
    docs = []

    if not os.path.exists(folder):
        return docs

    for fname in os.listdir(folder):
        if not fname.endswith(".json"):
            continue

        path = os.path.join(folder, fname)
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            docs.append({
                "id": fname,
                "data": data
            })
        except Exception as e:
            print(f"Failed to load {fname}: {e}")

    return docs


def get_document_by_id(doc_id: str):
    """
    Helper function to fetch a document by filename.
    """
    docs = load_all_json_docs(DOCLING_FOLDER)
    for doc in docs:
        if doc["id"] == doc_id:
            return doc
    return None


# ===== Request models =====
class ChatRequest(BaseModel):
    doc_id: str
    query: str


class TrustRequest(BaseModel):
    doc_id: str


class ExtractRequest(BaseModel):
    doc_id: str


class EvaluateRequest(BaseModel):
    doc_id: str
    topic: str


# ===== API endpoints =====

@app.get("/api/docs")
def list_documents():
    """
    List all available document IDs.
    Used by frontend to show selectable documents.
    """
    docs = load_all_json_docs(DOCLING_FOLDER)
    return {
        "documents": [d["id"] for d in docs]
    }


@app.post("/api/chat")
def chat_with_document(req: ChatRequest):
    """
    Chat with a specific document.

    This corresponds to:
    Task 4: Chat with Document
    """
    doc = get_document_by_id(req.doc_id)
    if doc is None:
        return {"error": "Document not found"}

    # Extract relevant text sections from the document
    doc_text = extract_key_sections(doc["data"])

    # Call your existing chat logic
    answer = chat_about_document(doc_text, req.query)

    return {
        "reply": answer
    }


@app.post("/api/trust")
def check_trustworthiness(req: TrustRequest):
    """
    Check document trustworthiness.

    This corresponds to:
    Task 1: Check Trustworthiness
    """
    doc = get_document_by_id(req.doc_id)
    if doc is None:
        return {"error": "Document not found"}

    text = extract_key_sections(doc["data"])
    metadata = extract_metadata_heuristics(doc["data"])

    result = trust_checker(text)

    return {
        "metadata": metadata,
        "trust_result": result
    }


@app.post("/api/extract")
def extract_information(req: ExtractRequest):
    """
    Extract entities / structured information from document.

    This corresponds to:
    Task 2: Extract Information
    """
    doc = get_document_by_id(req.doc_id)
    if doc is None:
        return {"error": "Document not found"}

    text = extract_key_sections(doc["data"])
    entities = extract_entities(text)

    return {
        "entities": entities
    }


@app.post("/api/evaluate")
def evaluate_relevance(req: EvaluateRequest):
    """
    Evaluate document relevance to a given topic.

    This corresponds to:
    Task 3: Evaluate Relevance
    """
    doc = get_document_by_id(req.doc_id)
    if doc is None:
        return {"error": "Document not found"}

    text = extract_key_sections(doc["data"])
    evaluation = evaluate_importance(text, req.topic)

    return {
        "evaluation": evaluation
    }
